//============================================================================
// Name        : serviceUserService.cpp
// Author      : Kiran Mohan E
// Version     : 1.0
// Copyright   : Copyright (c) 2016 Kiran Mohan E,  All Rights Reserved.
// Description : User Service using ONC RPC. This file defines the
//               user service remote protocol.
//============================================================================

#include <iostream>
#include "userService.h" /* user-service.h generated by rpcgen
                            from lib-user-service/user-service.x*/
using namespace std;

int * printmessage_1_svc(char **msg, struct svc_req *req)
{
   static int result; /* must be static! */

   cout << "Message receive [" << *msg << endl;

   result = 1;
   return (&result);
}

int main(int argc, char **argv) {
    cout << "Starting user service server..." << endl;
	int result = rpcServiceMain(argc, argv);
	return 0;
}
