//============================================================================
// Name        : serverUserService.cpp
// Author      : Kiran Mohan E
// Version     : 1.0
// Copyright   : Copyright (c) 2016 Kiran Mohan E,  All Rights Reserved.
// Description : User Service using ONC RPC. This file defines the
//               user service remote protocol.
//============================================================================

#include <iostream>
#include "userService.h" /* user-service.h generated by rpcgen
                            from lib-user-service/user-service.x*/
using namespace std;

result * sign_up_1_svc(user_profile * user, struct svc_req * svcReq)
{
   static result res; /* must be static! */

   /* free the previous result */
   res.status = 0;
   if ( res.resultData != NULL ) {
       delete res.resultData;
   }

   cout << "received request to register user " << user->username << endl;

   /*
    * do the work.
    */

   /* set the results and return */
   res.resultData = new char[MAXSTRINGLEN];
   sprintf(res.resultData, "it works");
   return &res;
}

//int main(int argc, char **argv) {
//    cout << "Starting user service server..." << endl;
//	int result = rpcServiceMain(argc, argv);
//	return 0;
//}
