/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _USERSERVICE_H_RPCGEN
#define _USERSERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRINGLEN 255

typedef char *String;

struct result {
	int status;
	String resultData;
};
typedef struct result result;

struct user_profile {
	String username;
	String password;
};
typedef struct user_profile user_profile;

#define USER_SERVICE 0x20000001
#define USER_SERVICE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SIGN_UP 1
extern  result * sign_up_1(user_profile *, CLIENT *);
extern  result * sign_up_1_svc(user_profile *, struct svc_req *);
#define LOGIN 2
extern  result * login_1(user_profile *, CLIENT *);
extern  result * login_1_svc(user_profile *, struct svc_req *);
extern int user_service_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SIGN_UP 1
extern  result * sign_up_1();
extern  result * sign_up_1_svc();
#define LOGIN 2
extern  result * login_1();
extern  result * login_1_svc();
extern int user_service_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_String (XDR *, String*);
extern  bool_t xdr_result (XDR *, result*);
extern  bool_t xdr_user_profile (XDR *, user_profile*);

#else /* K&R C */
extern bool_t xdr_String ();
extern bool_t xdr_result ();
extern bool_t xdr_user_profile ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_USERSERVICE_H_RPCGEN */
