/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "userService.h"

bool_t
xdr_String (XDR *xdrs, String *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_result (XDR *xdrs, result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_String (xdrs, &objp->resultData))
		 return FALSE;
	return TRUE;
}
